runtime: nodejs16

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

env_variables:
  REFRESH_TOKEN_SECRET: '09f26e402586e2faa8da4c98a35f1b20d6b033c'
  ACCESS_TOKEN_SECRET: '09f26e402586e2faa8da4c98a35f1b20d6b033c'

automatic_scaling:
  min_idle_instances: 1